"""empty message

Revision ID: b5c1c534c21b
Revises: b29bf9df0547
Create Date: 2022-10-08 17:40:24.637438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c1c534c21b'
down_revision = 'b29bf9df0547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('pet_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'pet_type')
    # ### end Alembic commands ###
